name: ui_trangsuc_vs2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.5.2
  provider: ^6.0.5
  intl: ^0.18.0
  shimmer: ^2.0.0
  image_picker: ^1.0.4
  image: ^4.1.3
  camera: ^0.10.5+2
  camera_web: ^0.3.2+1
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3+4
  url_launcher: ^6.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/fonts/
  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 700
